name: Release
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
          # cache: 'npm'
          # registry-url: 'https://registry.npmjs.org'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm test
      # Publish to npm (done locally)
      # - run: npm publish --access public
        # env:
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Setup .npmrc file to publish to GitHub Packages
      # - uses: actions/setup-node@v2.4.0
        # with:
          # node-version: '14.x'
          # cache: 'npm'
          # registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@TropicalRaisel'
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
