# https://snyk.io/blog/github-actions-to-securely-publish-npm-packages/
# https://docs.github.com/en/actions/guides/publishing-nodejs-packages
name: Release
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
