name: Release
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@TropicalRaisel'
      - run: pnpm i
      - run: pnpm test
      # Publish to GitHub Packages
      - run: pnpm publish --access public --no-git-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
