name: Test

on:
  push:
    branches:
      # - main
      - master

  pull_request:
    branches:
      # - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: pnpm add esbuild -g

      - name: Install
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Test
        run: pnpm test
        env:
          CI: true
